spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    #drop n create table again, good for testing, comment this in production
    #spring.jpa.hibernate.ddl-auto=create
  datasource:
    url: jdbc:postgresql://ep-shy-salad-a1y03nrr.ap-southeast-1.pg.koyeb.app/koyebdb
    username: koyeb-adm
    password: bSWV0vAIj7Xf
cloudinary:
  url: cloudinary://149924232464535:bHDB80pKyomXrFyeYxs5AnyAIc0@djmhm13uu
  cloudName: djmhm13uu
  apiKey: '149924232464535'
  apiSecret: bHDB80pKyomXrFyeYxs5AnyAIc0