spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    #drop n create table again, good for testing, comment this in production
    #spring.jpa.hibernate.ddl-auto=create
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com/postgres
    username: postgres.yvpocqcwnqnizjlvxexz
    password: J8nHEW50yRmAJs41
cloudinary:
  url: cloudinary://149924232464535:bHDB80pKyomXrFyeYxs5AnyAIc0@djmhm13uu
  cloudName: djmhm13uu
  apiKey: '149924232464535'
  apiSecret: bHDB80pKyomXrFyeYxs5AnyAIc0