spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'false'
    #drop n create table again, good for testing, comment this in production
    #spring.jpa.hibernate.ddl-auto=create
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com/postgres
    username: postgres.yvpocqcwnqnizjlvxexz
    password: J8nHEW50yRmAJs41
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
cloudinary:
  url: cloudinary://149924232464535:bHDB80pKyomXrFyeYxs5AnyAIc0@djmhm13uu
  cloudName: djmhm13uu
  folderName: bookery
  apiKey: '149924232464535'
  apiSecret: bHDB80pKyomXrFyeYxs5AnyAIc0